version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: ci-frontend
        command: npm run start
        ports:
            - "3000:3000"
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ./frontend/src:/usr/src/app/src

    api:
        build: ./api
        container_name: ci-api
        command: npm i -g @nestjs/cli
        command: npm run start
        restart: unless-stopped
        ports:
            - "3001:3001"  
        environment:
            - PORT=3001
            - MONGO_URL=mongodb://api_db:27017/api
        depends_on: 
            - api_db        
    auth:
        build: ./auth
        container_name: ci-auth
        command: npm run start
        restart: unless-stopped
        ports:
            - "3002:3002"
        environment: 
            - PORT=3002
            - MONGO_URL=mongodb://auth_db:27017/auth
        depends_on:
            - auth_db
    
    api_db:
        image: mongo:latest
        container_name: ci-api-db
        volumes:
            - mongodb_api:/data/d b
    
    auth_db:
        image: mongo:latest
        container_name: ci-auth-db
        volumes: 
            - mongodb_auth:/data/db

volumes: 
    mongodb_api:
    mongodb_auth: